version: 2

dependencies:
  override:
    - sudo

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.4.0
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependency
          command: npm install && npm install --save-dev firebase-tools
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: deploy
          command: firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
