version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependency 
          command: npm install 
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
  deploy:
    working_directory: ~/workspace
    docker:
      - image: node:9.4.0
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Install Dependency
            command: sudo npm install -g firebase-tools
        - deploy:
            command: firebase deploy --token "$FIREBASE_TOKEN"


workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only: master

